spring.application.name=barbershop-backend
spring.data.mongodb.uri=mongodb://localhost:27017/barber

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true