spring.application.name=barbershop-backend

#spring.datasource.url=jdbc:mysql://localhost:3306/barbershop
#spring.datasource.username=root
#spring.datasource.password=prateek26
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


spring.data.mongodb.uri=mongodb://localhost:27017/barbershop
spring.data.mongodb.database=barbershop

spring.data.mongodb.repositories.enabled=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aashusharma8897@gmail.com
spring.mail.password=ikltzqkbvudenxii
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

