spring.application.name=barbershop-backend
spring.data.mongodb.uri=mongodb://localhost:27017/barber

<<<<<<< HEAD
#spring.datasource.url=jdbc:mysql://localhost:3306/barbershop
#spring.datasource.username=root
#spring.datasource.password=prateek26
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# MongoDB connection URI
spring.data.mongodb.uri=mongodb://localhost:27017/barbershop

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aashusharma8897@gmail.com
spring.mail.password=ldim jpbg saic upto
=======
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=your-app-password
>>>>>>> 5a7d2a83293840a71efa8973dfd5ed59e7d1f1ca
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true